# Generated by Django 5.1 on 2024-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRODUCT_AVAILABLE", "AVAILABLE"),
                    ("PRODUCT_RESERVED", "RESERVED"),
                    ("PRODUCT_UNAVAILABLE", "UNAVAILABLE"),
                ],
                default="PRODUCT_AVAILABLE",
                max_length=30,
            ),
        ),
    ]
