# Generated by Django 5.1 on 2024-08-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_email"),
        ("product", "0004_alter_product_status"),
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("customer", "product", "reservation_date")},
        ),
    ]
